package br.com.fitnesspro.scheduler.ui.screen.details.enums

enum class EnumSchedulerDetailsTags {
    SCHEDULER_DETAILS_SCREEN_FAB_ADD,
    SCHEDULER_DETAILS_SCREEN_ITEM_LIST,
    SCHEDULER_DETAILS_SCREEN_ITEM_LIST_LABELED_TEXT_NAME,
    SCHEDULER_DETAILS_SCREEN_ITEM_LIST_LABELED_TEXT_HOUR,
    SCHEDULER_DETAILS_SCREEN_ITEM_LIST_LABELED_TEXT_SITUATION,
    SCHEDULER_DETAILS_SCREEN_ITEM_LIST_LABELED_TEXT_PROFESSIONAL,
    SCHEDULER_DETAILS_SCREEN_ITEM_LIST_COMPROMISE_TYPE,

}