package br.com.fitnesspro.ui.screen.home.enums

enum class EnumHomeScreenTestTags {
    HOME_SCREEN_ACCOUNT_BUTTON,
    HOME_SCREEN_NOTIFICATIONS_BUTTON,
    HOME_SCREEN_LOGOUT_BUTTON,
    HOME_SCREEN_BUTTON_SCHEDULER,
    HOME_SCREEN_BUTTON_WORKOUT,
    HOME_SCREEN_BUTTON_NUTRITION,
}