package br.com.fitnesspro.common.ui.screen.registeruser.enums

enum class EnumRegisterAcademyTestTags {
    REGISTER_ACADEMY_SCREEN_FIELD_ACADEMY,
    REGISTER_ACADEMY_SCREEN_FIELD_DAY_WEEK,
    REGISTER_ACADEMY_SCREEN_FIELD_START,
    REGISTER_ACADEMY_SCREEN_FIELD_END,

    REGISTER_ACADEMY_SCREEN_FAB_SAVE,
    REGISTER_ACADEMY_ACTION_BUTTON_DELETE,

    REGISTER_ACADEMY_DIALOG_ACADEMIES_LIST_ITEM
}