package br.com.fitnesspro.common.ui.screen.registeruser.enums

enum class EnumRegisterUserScreenTestTags {
    REGISTER_USER_SCREEN_FAB_SAVE,
    REGISTER_USER_SCREEN_FAB_ADD,

    REGISTER_USER_SCREEN_TAB_GENERAL,
    REGISTER_USER_SCREEN_TAB_GENERAL_FIELD_NAME,
    REGISTER_USER_SCREEN_TAB_GENERAL_FIELD_EMAIL,
    REGISTER_USER_SCREEN_TAB_GENERAL_FIELD_PASSWORD,
    REGISTER_USER_SCREEN_TAB_GENERAL_FIELD_BIRTH_DATE,
    REGISTER_USER_SCREEN_TAB_GENERAL_FIELD_PHONE,

    REGISTER_USER_SCREEN_TAB_ACADEMY,
    REGISTER_USER_SCREEN_TAB_ACADEMY_LIST_ITEM,
    REGISTER_USER_SCREEN_TAB_ACADEMY_LIST_ITEM_LABELED_DAY_WEEK,
    REGISTER_USER_SCREEN_TAB_ACADEMY_LIST_ITEM_LABELED_TIME,

}