package br.com.fitnesspro.common.usecase.scheduler.enums

enum class EnumSchedulerConfigValidationTypes {
    REQUIRED_MIN_SCHEDULE_DENSITY,
    REQUIRED_MAX_SCHEDULE_DENSITY,
    REQUIRED_NOTIFICATION_ANTECEDENCE_TIME,

    INVALID_MIN_SCHEDULE_DENSITY,
    INVALID_MAX_SCHEDULE_DENSITY,
    INVALID_NOTIFICATION_ANTECEDENCE_TIME,

    INVALID_DENSITY_RANGE,
}