package br.com.fitnesspro.common.usecase.scheduler.enums

enum class EnumSchedulerConfigValidationTypes {
    REQUIRED_MIN_SCHEDULE_DENSITY,
    REQUIRED_MAX_SCHEDULE_DENSITY,
    REQUIRED_START_WORK_TIME,
    REQUIRED_END_WORK_TIME,
    REQUIRED_START_BREAK_TIME,
    REQUIRED_END_BREAK_TIME,

    INVALID_MIN_SCHEDULE_DENSITY,
    INVALID_MAX_SCHEDULE_DENSITY,

    INVALID_DENSITY_RANGE,
    INVALID_WORK_PERIOD,
    INVALID_BREAK_PERIOD
}