package br.com.fitnesspro.scheduler.ui.screen.scheduler.enums

enum class EnumSchedulerScreenTestTags {
    SCHEDULER_SCREEN_BUTTON_CONFIG,
    SCHEDULER_SCREEN_RECURRENT_SCHEDULE_FAB,
    SCHEDULER_SCREEN_BACK_MONTH_BUTTON,
    SCHEDULER_SCREEN_FORWARD_MONTH_BUTTON,
    SCHEDULER_SCREEN_LABEL_YEAR_MONTH,
    SCHEDULER_SCREEN_DAY_CELL
}