package br.com.fitnesspro.scheduler.ui.screen.scheduler.enums

enum class EnumSchedulerConfigScreenTestTags {
    SCHEDULER_CONFIG_SCREEN_LABEL_GENERAL,
    SCHEDULER_CONFIG_SCREEN_LABELED_SWITCH_BUTTON_ALARM,
    SCHEDULER_CONFIG_SCREEN_LABELED_SWITCH_BUTTON_NOTIFICATION,

    SCHEDULER_CONFIG_SCREEN_LABEL_DENSITY_EVENTS,
    SCHEDULER_CONFIG_SCREEN_LABEL_DENSITY_EVENTS_EXPLANATION,
    SCHEDULER_CONFIG_SCREEN_MIN_DENSITY_FIELD,
    SCHEDULER_CONFIG_SCREEN_MAX_DENSITY_FIELD,

    SCHEDULER_CONFIG_SCREEN_LABEL_WORK_TIME,
    SCHEDULER_CONFIG_SCREEN_LABEL_WORK_TIME_EXPLANATION,
    SCHEDULER_CONFIG_SCREEN_START_WORK_TIME_FIELD,
    SCHEDULER_CONFIG_SCREEN_END_WORK_TIME_FIELD,

    SCHEDULER_CONFIG_SCREEN_LABEL_BREAK_TIME,
    SCHEDULER_CONFIG_SCREEN_LABEL_BREAK_TIME_EXPLANATION,
    SCHEDULER_CONFIG_SCREEN_START_BREAK_TIME_FIELD,
    SCHEDULER_CONFIG_SCREEN_END_BREAK_TIME_FIELD,

    SCHEDULER_CONFIG_SCREEN_FAB_SAVE
}