package br.com.fitnesspro.scheduler.usecase.scheduler.enums

enum class EnumCompromiseValidationTypes {
    REQUIRED_MEMBER,
    REQUIRED_PROFESSIONAL,
    REQUIRED_HOUR_START,
    REQUIRED_HOUR_END,
    REQUIRED_DATE_START,
    REQUIRED_DATE_END,
    REQUIRED_DAY_OF_WEEKS,

    INVALID_HOUR_PERIOD,
    INVALID_DATE_PERIOD,

    MAX_LENGTH_OBSERVATION,

    START_HOUR_IN_PAST_TODAY,
    START_HOUR_WITHOUT_ONE_HOUR_ANTECEDENCE_TODAY,
    START_HOUR_OUT_OF_WORK_TIME_RANGE,
    END_HOUR_OUT_OF_WORK_TIME_RANGE,
    SCHEDULER_CONFLICT_MEMBER,
    RECURRENT_SCHEDULER_CONFLICT
}