package br.com.fitnesspro.scheduler.ui.screen.compromisse.enums

enum class EnumCompromiseScreenTags {
    COMPROMISE_SCREEN_PROFESSIONAL_FIELD,
    COMPROMISE_SCREEN_MEMBER_FIELD,
    COMPROMISE_SCREEN_START_DATE_FIELD,
    COMPROMISE_SCREEN_END_DATE_FIELD,
    COMPROMISE_SCREEN_START_HOUR_FIELD,
    COMPROMISE_SCREEN_END_HOUR_FIELD,
    COMPROMISE_SCREEN_OBSERVATION_FIELD,
    COMPROMISE_SCREEN_DAY_WEEKS_SELECTOR,

    COMPROMISE_SCREEN_LABELED_TEXT_NAME,
    COMPROMISE_SCREEN_LABELED_TEXT_MEMBER,
    COMPROMISE_SCREEN_LABELED_TEXT_PROFESSIONAL,
    COMPROMISE_SCREEN_LABELED_TEXT_HOUR,
    COMPROMISE_SCREEN_LABELED_TEXT_SITUATION,
    COMPROMISE_SCREEN_LABELED_TEXT_DATA_CANCEL,
    COMPROMISE_SCREEN_LABELED_TEXT_CANCELLATION_PERSON,
    COMPROMISE_SCREEN_LABELED_TEXT_OBSERVATION,

    COMPROMISE_SCREEN_FAB_SAVE,
    COMPROMISE_SCREEN_SAVE_KEYBOARD_DONE,
    COMPROMISE_SCREEN_ACTION_DELETE,
    COMPROMISE_SCREEN_ACTION_MESSAGE,
    COMPROMISE_SCREEN_ACTION_SCHEDULE_CONFIRM,

    COMPROMISE_SCREEN_DIALOG_LIST_ITEM,
    COMPROMISE_SCREEN_DIALOG_LIST_ITEM_LABEL
}