name: Execução dos Testes e Build do APK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Gradle
        run: |
          GRADLE_VERSION=8.8
          wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
          sudo mkdir /opt/gradle
          sudo unzip -d /opt/gradle gradle-${GRADLE_VERSION}-bin.zip
          echo "export PATH=/opt/gradle/gradle-${GRADLE_VERSION}/bin:\$PATH" >> $GITHUB_ENV
          gradle --version

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Install Android Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d latest
          rm commandlinetools.zip
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:\$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Set Android SDK Version
        run: |
          echo "export ANDROID_SDK_ROOT=\$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=\$ANDROID_SDK_ROOT/platform-tools:\$PATH" >> $GITHUB_ENV
          echo "export PATH=\$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:\$PATH" >> $GITHUB_ENV
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34"

      - name: Run Unit Tests
        run: gradle testDebugUnitTest

      - name: Build APK
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
