name: Android Build & Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Fix Gradle Wrapper Permissions
        run: chmod +x ./gradlew

      - name: Decode Keystore
        if: env.KEYSTORE_BASE64 != ''
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Extract Version Name
        id: version
        run: |
          VERSION_NAME=$(grep "versionName" app/build.gradle.kts | head -n1 | sed -E 's/.*versionName\s*=\s*\"([^\"]+)\".*/\1/')
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release APK
        env:
          KEYSTORE_PATH: keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=$KEYSTORE_PATH \
          -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
          -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
          -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      - name: Upload APKs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-apks
          path: |
            $(find . -name '*debug*.apk' | head -n1)
            $(find . -name '*release*.apk' | head -n1)

  release:
    name: Create Tag and GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Download built APKs
        uses: actions/download-artifact@v4
        with:
          name: built-apks

      - name: Extract Version Name
        id: version
        run: |
          VERSION_NAME=$(grep "versionName" app/build.gradle.kts | head -n1 | sed -E 's/.*versionName\s*=\s*\"([^\"]+)\".*/\1/')
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT

      - name: Create tag from versionName
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch --tags
          git tag "v${{ steps.version.outputs.version_name }}"
          git push origin "v${{ steps.version.outputs.version_name }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version_name }}
          name: v${{ steps.version.outputs.version_name }}
          files: |
            **/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
