name: Execução dos Testes e Build do APK

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      #      - name: Install Gradle
      #        run: |
      #          GRADLE_VERSION=8.8
      #          wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
      #          sudo mkdir /opt/gradle
      #          sudo unzip -d /opt/gradle gradle-${GRADLE_VERSION}-bin.zip
      #          echo "export PATH=/opt/gradle/gradle-${GRADLE_VERSION}/bin:\$PATH" >> $GITHUB_ENV
      #          gradle --version

      #      - name: Cache Gradle dependencies
      #        uses: actions/cache@v4
      #        with:
      #          path: |
      #            ~/.gradle/caches
      #            ~/.gradle/wrapper
      #          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #          restore-keys: |
      #            ${{ runner.os }}-gradle

      #      - name: Set Android SDK Version
      #        run: |
      #          echo "export ANDROID_SDK_ROOT=\$HOME/android-sdk" >> $GITHUB_ENV
      #          echo "export PATH=\$ANDROID_SDK_ROOT/platform-tools:\$PATH" >> $GITHUB_ENV
      #          echo "export PATH=\$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:\$PATH" >> $GITHUB_ENV
      #          yes | sdkmanager --licenses
      #          sdkmanager "platforms;android-34"

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

#      - name: Run Unit Tests
#        run: ./gradlew testDebugUnitTest

      - name: Run Tests
        run: ./gradlew test --tests "*"

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
