name: Create Release

# Define que o workflow será disparado manualmente
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
      release_notes:
        description: 'Release notes or description'
        required: false

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Checkout o código
      - name: Checkout code
        uses: actions/checkout@v3

      # Gera o APK (caso necessário)
      - name: Build APK
        run: ./gradlew assembleRelease

      # Anexa o APK e cria uma release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          release_name: ${{ github.event.inputs.release_version }}
          body: ${{ github.event.inputs.release_notes || 'No release notes provided.' }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      # Faz o upload do APK para a release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: app-release-${{ github.event.inputs.release_version }}.apk
          asset_content_type: application/vnd.android.package-archive
