name: Build APK Manually

on:
  workflow_dispatch:  # Executado manualmente

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew

      - name: Download Test Results
        uses: actions/download-artifact@v3
        with:
          name: test-results

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk
